// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    [Index(nameof(CouponIdvalue), Name = "UQ_Coupons_CouponIDValue", IsUnique = true)]
    internal partial class Coupon
    {
        public Coupon()
        {
            JobDetails = new HashSet<JobDetail>();
            Sales = new HashSet<Sale>();
        }

        [Key]
        [Column("CouponID")]
        public int CouponId { get; set; }
        [Required]
        [Column("CouponIDValue")]
        [StringLength(10)]
        public string CouponIdvalue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        public int CouponDiscount { get; set; }
        public int SalesOrService { get; set; }

        [InverseProperty(nameof(JobDetail.Coupon))]
        public virtual ICollection<JobDetail> JobDetails { get; set; }
        [InverseProperty(nameof(Sale.Coupon))]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}