// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    internal partial class CustomerVehicle
    {
        public CustomerVehicle()
        {
            Jobs = new HashSet<Job>();
        }

        [Key]
        [StringLength(13)]
        public string VehicleIdentification { get; set; }
        [Required]
        [StringLength(20)]
        public string Make { get; set; }
        [Required]
        [StringLength(30)]
        public string Model { get; set; }
        [Column("CustomerID")]
        public int CustomerId { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("CustomerVehicles")]
        public virtual Customer Customer { get; set; }
        [InverseProperty(nameof(Job.VehicleIdentificationNavigation))]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}