// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    internal partial class JobDetailPart
    {
        [Key]
        [Column("JobDetailPartID")]
        public int JobDetailPartId { get; set; }
        [Column("JobDetailID")]
        public int JobDetailId { get; set; }
        [Column("PartID")]
        public int PartId { get; set; }
        public short Quantity { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal SellingPrice { get; set; }

        [ForeignKey(nameof(JobDetailId))]
        [InverseProperty("JobDetailParts")]
        public virtual JobDetail JobDetail { get; set; }
        [ForeignKey(nameof(PartId))]
        [InverseProperty("JobDetailParts")]
        public virtual Part Part { get; set; }
    }
}