// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    internal partial class PurchaseOrderDetail
    {
        public PurchaseOrderDetail()
        {
            ReceiveOrderDetails = new HashSet<ReceiveOrderDetail>();
            ReturnedOrderDetails = new HashSet<ReturnedOrderDetail>();
        }

        [Key]
        [Column("PurchaseOrderDetailID")]
        public int PurchaseOrderDetailId { get; set; }
        [Column("PurchaseOrderID")]
        public int PurchaseOrderId { get; set; }
        [Column("PartID")]
        public int PartId { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        public decimal PurchasePrice { get; set; }
        [StringLength(50)]
        public string VendorPartNumber { get; set; }

        [ForeignKey(nameof(PartId))]
        [InverseProperty("PurchaseOrderDetails")]
        public virtual Part Part { get; set; }
        [ForeignKey(nameof(PurchaseOrderId))]
        [InverseProperty("PurchaseOrderDetails")]
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [InverseProperty(nameof(ReceiveOrderDetail.PurchaseOrderDetail))]
        public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; }
        [InverseProperty(nameof(ReturnedOrderDetail.PurchaseOrderDetail))]
        public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; }
    }
}