// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    internal partial class ReceiveOrder
    {
        public ReceiveOrder()
        {
            ReceiveOrderDetails = new HashSet<ReceiveOrderDetail>();
            ReturnedOrderDetails = new HashSet<ReturnedOrderDetail>();
        }

        [Key]
        [Column("ReceiveOrderID")]
        public int ReceiveOrderId { get; set; }
        [Column("PurchaseOrderID")]
        public int PurchaseOrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ReceiveDate { get; set; }
        [Column("EmployeeID")]
        public int EmployeeId { get; set; }

        [ForeignKey(nameof(PurchaseOrderId))]
        [InverseProperty("ReceiveOrders")]
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [InverseProperty(nameof(ReceiveOrderDetail.ReceiveOrder))]
        public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; }
        [InverseProperty(nameof(ReturnedOrderDetail.ReceiveOrder))]
        public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; }
    }
}