// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    internal partial class Sale
    {
        public Sale()
        {
            SaleDetails = new HashSet<SaleDetail>();
            SaleRefunds = new HashSet<SaleRefund>();
        }

        [Key]
        [Column("SaleID")]
        public int SaleId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SaleDate { get; set; }
        [Column("EmployeeID")]
        public int EmployeeId { get; set; }
        [Column(TypeName = "money")]
        public decimal TaxAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal SubTotal { get; set; }
        [Column("CouponID")]
        public int? CouponId { get; set; }
        [Required]
        [StringLength(1)]
        public string PaymentType { get; set; }

        [ForeignKey(nameof(CouponId))]
        [InverseProperty("Sales")]
        public virtual Coupon Coupon { get; set; }
        [ForeignKey(nameof(EmployeeId))]
        [InverseProperty("Sales")]
        public virtual Employee Employee { get; set; }
        [InverseProperty(nameof(SaleDetail.Sale))]
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
        [InverseProperty(nameof(SaleRefund.Sale))]
        public virtual ICollection<SaleRefund> SaleRefunds { get; set; }
    }
}