// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    internal partial class SaleRefund
    {
        public SaleRefund()
        {
            SaleRefundDetails = new HashSet<SaleRefundDetail>();
        }

        [Key]
        [Column("SaleRefundID")]
        public int SaleRefundId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SaleRefundDate { get; set; }
        [Column("SaleID")]
        public int SaleId { get; set; }
        [Column("EmployeeID")]
        public int EmployeeId { get; set; }
        [Column(TypeName = "money")]
        public decimal TaxAmount { get; set; }
        [Column(TypeName = "money")]
        public decimal SubTotal { get; set; }

        [ForeignKey(nameof(EmployeeId))]
        [InverseProperty("SaleRefunds")]
        public virtual Employee Employee { get; set; }
        [ForeignKey(nameof(SaleId))]
        [InverseProperty("SaleRefunds")]
        public virtual Sale Sale { get; set; }
        [InverseProperty(nameof(SaleRefundDetail.SaleRefund))]
        public virtual ICollection<SaleRefundDetail> SaleRefundDetails { get; set; }
    }
}