// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Receiving.Entities
{
    [Table("UnorderedPurchaseItemCart")]
    internal partial class UnorderedPurchaseItemCart
    {
        [Key]
        [Column("CartID")]
        public int CartId { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [StringLength(50)]
        public string VendorPartNumber { get; set; }
        public int Quantity { get; set; }
    }
}