// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Backend_Purchasing.Entities
{
    internal partial class Vendor
    {
        public Vendor()
        {
            Parts = new HashSet<Part>();
            PurchaseOrders = new HashSet<PurchaseOrder>();
        }

        [Key]
        [Column("VendorID")]
        public int VendorId { get; set; }
        [Required]
        [StringLength(100)]
        public string VendorName { get; set; }
        [Required]
        [StringLength(12)]
        public string Phone { get; set; }
        [Required]
        [StringLength(30)]
        public string Address { get; set; }
        [Required]
        [StringLength(30)]
        public string City { get; set; }
        [Required]
        [Column("ProvinceID")]
        [StringLength(2)]
        public string ProvinceId { get; set; }
        [Required]
        [StringLength(6)]
        public string PostalCode { get; set; }

        [InverseProperty(nameof(Part.Vendor))]
        public virtual ICollection<Part> Parts { get; set; }
        [InverseProperty(nameof(PurchaseOrder.Vendor))]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}