// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend_SalesReturns.Entities
{
    internal partial class Category
    {
        public Category()
        {
            Parts = new HashSet<Part>();
        }

        public int CategoryID { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Part> Parts { get; set; }
    }
}